### ISSUE TITLE
new 30arcsec GMTED dataset

### ISSUE THREAD

**Issue by adamrher** [NCAR/Topo#10]
New topography dataset. It is the old GMTED2010 dataset merged with the GrIS and AIS high resolution bedmachine data, for more accurate representation of ice sheets. Here is what a ne30pg3 topofile looks like using this new dataset minus the old dataset:

![temp_topo BM](https://user-images.githubusercontent.com/29961476/125525714-2bf24c4a-9f0e-4887-bad7-2cc6160d3690.png)

Among other changes, the ice sheets have steeper margins, which seems to produce larger subgrid heights. This is interesting b/c if you recall, SGH30 was artificially increased over Greenland in the old dataset to bring the surface winds into better agreement with observations. @whlipscomb @lofverstrom

Once https://github.com/NCAR/Topo/issues/9 is merged, I can modify the Makefile to point to the new 3km intermediate cubed-sphere dataset.

**Comment by whlipscomb** [comment]
@adamrher – Thanks, this is beautiful. It's interesting that Greenland is systematically higher (in the north) and Antarctica lower (almost everywhere), though maybe not by enough to see a difference in the climate.

**Comment by adamrher** [comment]
Another interesting difference in these datasets appears to be how they handle the polar orbit "blind spot" in Antarctica. See the difference plot here for the Antarctica var-res grid:

![temp_topo](https://user-images.githubusercontent.com/29961476/125855285-4d0399d6-4e80-46ab-95be-3ea310722e9a.png)

Looking into this a bit, GMTED2010 uses the Bamber et al 2008 dataset: "The new Antarctica model is a grid regularly spaced at 1-kilometer intervals and has been created from combined European Radar Satellite (ERS-1) radar data and ICESat laser satellite altimetry." So I suspect some void filling algorithm was used to fill in S.Pole blind spot in that dataset.

**Comment by PeterHjortLauritzen** [comment]
Great work @adamrher

How about we have Cecile do an F2000climo run with the new topography (to assess impact on climate) before me make this dataset the new default in the topo software?

**Comment by adamrher** [comment]
sure. I'm thinking we should do three f09 runs:

(1) a clean topo file w/ the old dataset
(2) a clean topo file w/ the new dataset
(3) the current f09 default topo file (uses the old dataset, but has enhanced SGH30 over GrIS)

**Comment by PeterHjortLauritzen** [comment]
New minor bug fix for BM elevation data from Rene: He had previously merged in non-Greenland land in the Greenland BM dataset. Now using GMTED for these situations.

![Screen Shot 2022-05-19 at 3 40 26 PM](https://user-images.githubusercontent.com/8782989/169409175-40392441-be91-4d6b-83a1-5fe0f94a7eab.png)

**Comment by dongli** [comment]
Dear all,

Thanks for this topo software! I would like to know where to find out this new GMTED dataset?
