### ISSUE TITLE
Add regression test to ensure bit-for-bit changes before making changes

### ISSUE THREAD

**Issue by MiCurry** [NCAR/Topo#14]
Before we make any major changes, creating a regression test to ensure we get the same results will be beneficial.

This issue serves as an area to discuss creating this regression test.

**Comment by MiCurry** [comment]
I think we should create a few 'control cases' that we can use to compare the tool going forward, which we could store on `glade`. We may also want to have their final `namelists`associated with them.

A good-enough regression test for this may be just taking the difference of a compare file with one that's generated with a new version. This could be done by hand using `ncdiff` or we could create a Python program that can be ran on `glade`.

We also may need to discuss, when we start to make major changes, if we expect the same settings to produce the same, or different results. At first, we can begin with comparing that namelists and output grids are bit-for-bit identical.

**Comment by MiCurry** [comment]
Somewhat along these lines, I would also like to discuss enabling to speed up development. If we plan to make changes to this tool, we (most likely I) simply can't anything more than 10 minutes for the code to finish running. We simply need a way to "run it fast".

We've done this for the init_atmosphere core for interpolating static fields. We simply have an option that subsamples the GMTED2010 dataset, so we can reduce the amount of points by a half, a fourth, etc. It generates the wrong results, but it runs extremely quickly.

This kind of 'feature' can help just to see everything is setup correctly. That filenames are being generated correctly, namelists are being read, arrays are being deallocated and there aren't any segfaults far down the execution. 

I have some 'hacky' ways that I do this, but does anyone have a recommendation for doing so in a different way?

**Comment by PeterHjortLauritzen** [comment]
Done
