### ISSUE TITLE
-z option not working

### ISSUE THREAD

**Issue by JulioTBacmeister** [NCAR/Topo#30]
For some reason the command below doesn't result in ldevelopment_diags=.TRUE.

./cube_to_target --grid_descriptor_file='../../regression-test-data/ne30pg3.nc' --intermediate_cs_name='../../regression-test-data/gmted2010_bedmachine-ncube0540.nc' --output_grid=$ogrid --coarse_radius=$Co --fine_radius=$Fi -r -u 'userid@ucar.edu' -q 'output/' -z

The additional output isn't written.

If I put the '-z' option right after the '-r' option I get the error:

"Required argument not specified: name_email_of_creator"

**Comment by PeterHjortLauritzen** [comment]
fixed
