### ISSUE TITLE
merge TopoCESM2 to master

### ISSUE THREAD

**Issue by adamrher** [NCAR/Topo#4]
Hi @gold2718 

@PeterHjortLauritzen and I talked about merging the TopoCESM2 branch to the head of master. There have been many updates to TopoCESM2 so I think it's time to just bring it in to master.

I'm making some tweaks right now and so will commit a final version of TopoCESM2 in a couple hours, but I just wanted to put out a feeler.

**Comment by PeterHjortLauritzen** [comment]
done
