### ISSUE TITLE
Always read in PHIS on GLL grid for spectral-elements

### ISSUE THREAD

**Issue by PeterHjortLauritzen** [NCAR/Topo#46]
Decide on naming convention for PHIS on GLL grid when using physics grid option. This will require changes in dyn_comp.F90 on cam_development (i.e. coordination needed).

See also issue https://github.com/ESCOMP/CAM/issues/552

**Comment by adamrher** [comment]
```PHIS_d```?

**Comment by JulioTBacmeister** [comment]
PHIS_d seems good to me.

**Comment by PeterHjortLauritzen** [comment]
Done https://github.com/ESCOMP/CAM/issues/552
