### ISSUE TITLE
Add GLL grid topo as well as lat_d, lon_d to topography file.

### ISSUE THREAD

**Issue by JulioTBacmeister** [NCAR/Topo#55]
I think we should have topography on both the phsygrid and the GLL grid in topography files for physgrid configurations e.g., ne30pg3

**Comment by PeterHjortLauritzen** [comment]
This option is available with "-grid_descriptor_file_gll". We will turn that on when we generate new "pg" topo files. This will be needed once https://github.com/ESCOMP/CAM/issues/552 is resolved.
