### ISSUE TITLE
bin_to_cube is broken

### ISSUE THREAD

**Issue by adamrher** [NCAR/Topo#60]
@Katetc found that ```bin_to_cube``` does not compile out of the box:

"However, we still call the bin_to_cube code, and that doesn't build on Derecho in the code I just cloned from [github.com/NCAR/topo](http://github.com/NCAR/topo). I'm getting the error:
NCAR_topo_clone/bin_to_cube> gmake -f Makefile
unknown option: --fc Usage: nc-config [OPTION]  Available values for OPTION include:    --help             display this help message and exit   --all    (plus many more):"

She later identified the problem:

"Ope, I figured it out. The Makefile in bin_to_cube points to a machine_settings.make file in the root directory and the Makefile in cube_to_target points to a machine_settings.make file in the local directory. And the later one has a ? on the equals sign that fixes all problems. 

So, you may need to update the machine_settings.make file in the root directory of NCAR/topo. I'll use the one from cube_to_target in the Icesheet build. I can get everything to build in NCAR/topo now, so I should be able to do the same for the Icesheet code."

**Comment by PeterHjortLauritzen** [comment]
fixed in commit 6bfa27d00d2a13eca4d7b12608e515e6e5e03562
